name: Node.js CI

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: |
          cd backend
          echo "NODE_ENV=${{ secrets.NODE_ENV }}" > .env
          echo "HOSTNAME=${{ secrets.HOSTNAME }}" >> .env
          echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" >> .env
          npm i
          cd ../frontend
          echo "VUE_APP_NODE_ENV=${{ secrets.NODE_ENV }}" > .env
          echo "VUE_APP_HOSTNAME=${{ secrets.HOSTNAME }}" >> .env
          echo "VUE_APP_NODE_ENV=${{ secrets.NODE_ENV }}" > .env.production
          echo "VUE_APP_HOSTNAME=${{ secrets.HOSTNAME }}" >> .env.production
          npm i
          npm run build
          cd ../backend
          npm run db:push
          cd ../
          pm2 kill
          pm2 start backend/src/server.js
          pm2 save --force
          sudo service nginx restart
