name: Node.js CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: |
          cd backend
          echo "NODE_ENV=${{ secrets.NODE_ENV }}" > .env
          echo "HOSTNAME=${{ secrets.HOSTNAME }}" >> .env
          echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" >> .env
          npm i
          cd ../frontend
          rm package-lock.json
          sudo apt remove -y nodejs
          sudo apt install -y nodejs
          sudo npm i -g node-sass@6.0.1
          npm i
          npm run build
          cd ../backend
          npm run db:push
          cd ../
          pm2 restart 0
          pm2 save
          sudo service nginx restart
